% \VignetteIndexEntry{CCEMS Manual} 
% \VignetteDepends{ccems}

\documentclass[12pt]{article}
\usepackage[OT1]{fontenc}
\usepackage{Sweave}
\begin{document}

\title{Combinatorially Complex\\ Equilibrium Model Selection}
\author{Tom Radivoyevitch}

\maketitle

\section{Introduction}
A conceptual overview of this package is given in the \texttt{ccems} help page.  Please read that 
first, then the help for
\texttt{ems} and \texttt{mkg}. An example of how
this package can be used to design subsequent experiments is given in RtExpDes.pdf in \texttt{doc}. 

This package is being developed for research in the dNTP supply enzymes ribonucleotide reductase
(a hexamer), thymidine kinase I (a tetramer) and II (a monomer-dimer) and deoxycytidine kinase (a dimer).  
Simple enzyme-substrate-inhibitor monomer enzyme models are not yet in this set and 
the software does not yet handle such 3-reactant systems. 
The software works in situations where there is one ligand
binding the protein, possibly at two different binding sites (of variable binding status) 
per monomer, and with no limit on the $j$-mer size $j$.  Developments to broader conditions will ensue 
as the author's research demands it.   

%<<deModel, results = hide, echo = FALSE>>=
%library(ccems)
%@








\end{document}
